name: Build and CLI executables

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: windows
            arch: amd64
          - os: windows
            arch: arm64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Embed release name
        if: github.event_name == 'release'
        run: echo "${{ github.event.release.tag_name }}" > cli/internal/update/version

      - name: Embed dummy version
        if: github.event_name != 'release'
        run: echo "v0.0.0" > cli/internal/update/version

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        run: |
          if [ "${{matrix.os}}" = "windows" ]; then
            echo "EXTENSION=.exe" >> $GITHUB_ENV
          else
            echo "EXTENSION=" >> $GITHUB_ENV
          fi
          go build -v -o ${{ github.event.repository.name }}-${{ matrix.os }}-${{ matrix.arch }} ./cli

      - name: Upload artifact
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ github.event.repository.name }}-${{ matrix.os }}-${{ matrix.arch }}
          asset_name: ${{ github.event.repository.name }}-${{ matrix.os }}-${{ matrix.arch }}${{ env.EXTENSION }}
          asset_content_type: application/octet-stream